  
#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

//Pines escogidos para el ATMega 2560. Dos registros: MODE para el DDx y SIGNAL para el PORTx

//Sensores infrarrojos
//Sensores infrarrojos delanteros

const uint8_t MODE_IR_1 = DDA0; //IR 1 -> SENSOR DELANTE 1 -> ARDUINO MEGA 22
const uint8_t MODE_IR_2 = DDA1;	//IR 2 -> SENSOR DELANTE 2 -> ARDUINO MEGA 23
const uint8_t MODE_IR_3 = DDA2; //IR 3 -> SENSOR DELANTE 3 -> ARDUINO MEGA 24
const uint8_t MODE_IR_4 = DDA3; //IR 4 -> SENSOR DELANTE 4 -> ARDUINO MEGA 25
const uint8_t MODE_IR_5 = DDA4; //IR 5 -> SENSOR DELANTE 5 -> ARDUINO MEGA 26
const uint8_t MODE_IR_6 = DDA5; //IR 6 -> SENSOR DELANTE 6 -> ARDUINO MEGA 27
const uint8_t MODE_IR_7 = DDA6; //IR 7 -> SENSOR DELANTE 7 -> ARDUINO MEGA 28

const uint8_t PULLUP_IR_1 = PORTA0; //IR 1 -> SENSOR DELANTE 1 -> ARDUINO MEGA 22
const uint8_t PULLUP_IR_2 = PORTA1; //IR 2 -> SENSOR DELANTE 2 -> ARDUINO MEGA 23
const uint8_t PULLUP_IR_3 = PORTA2; //IR 3 -> SENSOR DELANTE 3 -> ARDUINO MEGA 24
const uint8_t PULLUP_IR_4 = PORTA3; //IR 4 -> SENSOR DELANTE 4 -> ARDUINO MEGA 25
const uint8_t PULLUP_IR_5 = PORTA4; //IR 5 -> SENSOR DELANTE 5 -> ARDUINO MEGA 26
const uint8_t PULLUP_IR_6 = PORTA5; //IR 6 -> SENSOR DELANTE 6 -> ARDUINO MEGA 27
const uint8_t PULLUP_IR_7 = PORTA6; //IR 7 -> SENSOR DELANTE 7 -> ARDUINO MEGA 28

const uint8_t READ_IR_1 = PINA0; //IR 1 -> SENSOR DELANTE 1 -> ARDUINO MEGA 22
const uint8_t READ_IR_2 = PINA1; //IR 2 -> SENSOR DELANTE 2 -> ARDUINO MEGA 23
const uint8_t READ_IR_3 = PINA2; //IR 3 -> SENSOR DELANTE 3 -> ARDUINO MEGA 24
const uint8_t READ_IR_4 = PINA3; //IR 4 -> SENSOR DELANTE 4 -> ARDUINO MEGA 25
const uint8_t READ_IR_5 = PINA4; //IR 5 -> SENSOR DELANTE 5 -> ARDUINO MEGA 26
const uint8_t READ_IR_6 = PINA5; //IR 6 -> SENSOR DELANTE 6 -> ARDUINO MEGA 27
const uint8_t READ_IR_7 = PINA6; //IR 7 -> SENSOR DELANTE 7 -> ARDUINO MEGA 28

//Fin sensores infrarrojos delanteros
//Sensores infrarrojos traseros

const uint8_t MODE_IR_8 = DDC0; //IR 8 -> SENSOR DETRAS 1 -> ARDUINO MEGA 37
const uint8_t MODE_IR_9 = DDC1;	//IR 9 -> SENSOR DETRAS 2 -> ARDUINO MEGA 36
const uint8_t MODE_IR_10 = DDC2; //IR 10 -> SENSOR DETRAS 3 -> ARDUINO MEGA 35
const uint8_t MODE_IR_11 = DDC3; //IR 11 -> SENSOR DETRAS 4 -> ARDUINO MEGA 34
const uint8_t MODE_IR_12 = DDC4; //IR 12 -> SENSOR DETRAS 5 -> ARDUINO MEGA 33
const uint8_t MODE_IR_13 = DDC5; //IR 13 -> SENSOR DETRAS 6 -> ARDUINO MEGA 32
const uint8_t MODE_IR_14 = DDC6; //IR 14 -> SENSOR DETRAS 7 -> ARDUINO MEGA 31

const uint8_t PULLUP_IR_8 = PORTC0; //IR 8 -> SENSOR DETRAS 1 -> ARDUINO MEGA 37
const uint8_t PULLUP_IR_9 = PORTC1; //IR 9 -> SENSOR DETRAS 2 -> ARDUINO MEGA 36
const uint8_t PULLUP_IR_10 = PORTC2; //IR 10 -> SENSOR DETRAS 3 -> ARDUINO MEGA 35
const uint8_t PULLUP_IR_11 = PORTC3; //IR 11 -> SENSOR DETRAS 4 -> ARDUINO MEGA 34
const uint8_t PULLUP_IR_12 = PORTC4; //IR 12 -> SENSOR DETRAS 5 -> ARDUINO MEGA 33
const uint8_t PULLUP_IR_13 = PORTC5; //IR 13 -> SENSOR DETRAS 6 -> ARDUINO MEGA 32
const uint8_t PULLUP_IR_14 = PORTC6; //IR 14 -> SENSOR DETRAS 7 -> ARDUINO MEGA 31

const uint8_t READ_IR_8 = PINC0; //IR 8 -> SENSOR DETRAS 1 -> ARDUINO MEGA 37
const uint8_t READ_IR_9 = PINC1; //IR 9 -> SENSOR DETRAS 2 -> ARDUINO MEGA 36
const uint8_t READ_IR_10 = PINC2; //IR 10 -> SENSOR DETRAS 3 -> ARDUINO MEGA 35
const uint8_t READ_IR_11 = PINC3; //IR 11 -> SENSOR DETRAS 4 -> ARDUINO MEGA 34
const uint8_t READ_IR_12 = PINC4; //IR 12 -> SENSOR DETRAS 5 -> ARDUINO MEGA 33
const uint8_t READ_IR_13 = PINC5; //IR 13 -> SENSOR DETRAS 6 -> ARDUINO MEGA 32
const uint8_t READ_IR_14 = PINC6; //IR 14 -> SENSOR DETRAS 7 -> ARDUINO MEGA 31

//Fin sensores infrarrojos traseros
//Fin sensores infrarrojos 

//Servo 1 -> ARDUINO MEGA 2 -> ATMEGA PE4
//Servo 2 -> ARDUINO MEGA 3 -> ATMEGA PE5
//Servo 3 -> ARDUINO MEGA 4 -> ATMEGA PG5
//Servo 4 -> ARDUINO MEGA 5 -> ATMEGA PE3

//Motores
//Direcciones

const uint8_t MODE_DIRECCION_1 = DDL0; //DIRECCION DRIVER 1 -> ARDUINO MEGA 49
const uint8_t MODE_DIRECCION_2 = DDL1; //DIRECCION DRIVER 2 -> ARDUINO MEGA 48
const uint8_t MODE_DIRECCION_3 = DDL2; //DIRECCION DRIVER 3 -> ARDUINO MEGA 47
const uint8_t MODE_DIRECCION_4 = DDL3; //DIRECCION DRIVER 4 -> ARDUINO MEGA 46

const uint8_t SIGNAL_DIRECCION_1 = PORTL0; //DIRECCION DRIVER 1 -> ARDUINO MEGA 49
const uint8_t SIGNAL_DIRECCION_2 = PORTL1; //DIRECCION DRIVER 2 -> ARDUINO MEGA 48
const uint8_t SIGNAL_DIRECCION_3 = PORTL2; //DIRECCION DRIVER 3 -> ARDUINO MEGA 47
const uint8_t SIGNAL_DIRECCION_4 = PORTL3; //DIRECCION DRIVER 4 -> ARDUINO MEGA 46

//Fin direcciones
//Steps

const uint8_t MODE_STEPS_1 = DDL4; //STEPS DRIVER 1 -> ARDUINO MEGA 45
const uint8_t MODE_STEPS_2 = DDL5; //STEPS DRIVER 2 -> ARDUINO MEGA 44
const uint8_t MODE_STEPS_3 = DDL6; //STEPS DRIVER 3 -> ARDUINO MEGA 43
const uint8_t MODE_STEPS_4 = DDL7; //STEPS DRIVER 4 -> ARDUINO MEGA 42

const uint8_t SIGNAL_STEPS_1 = PORTL4; //STEPS DRIVER 1 -> ARDUINO MEGA 45
const uint8_t SIGNAL_STEPS_2 = PORTL5; //STEPS DRIVER 2 -> ARDUINO MEGA 44
const uint8_t SIGNAL_STEPS_3 = PORTL6; //STEPS DRIVER 3 -> ARDUINO MEGA 43
const uint8_t SIGNAL_STEPS_4 = PORTL7; //STEPS DRIVER 4 -> ARDUINO MEGA 42

//Fin steps
//Fin motores

//Radio

//MISO -> ATMEGA PB3 -> ARDUINO MEGA 50
//MOSI -> ATMEGA PB2 -> ARDUINO MEGA 51
//SCK -> ATMEGA PB1 -> ARDUINO MEGA 52
//SCN -> ATMEGA PB0 -> ARDUINO MEGA 53
//CE -> ATMEGA PG0 -> ARDUINO MEGA 41

//Fin radio

#endif
